#!/bin/bash

COMPOSE_FILE="../compose-development.yml"

# First argument is the service (e.g. composer, npm, artisan)
SERVICE=$1

# All remaining arguments are passed to the container command
shift

docker-compose -f "$COMPOSE_FILE" exec "$SERVICE" "$@"