#!/bin/bash

echo "Stopping Docker containers..."
docker compose -f compose-development.yml --env-file .env.development stop

if [ $? -eq 0 ]; then
    echo "Containers stopped successfully!"
    echo ""
    echo "Your Laravel development environment has been stopped."
    echo "To start it again, run: ./forge up"
    echo "To completely remove containers, run: ./forge down"
else
    echo "Failed to stop containers!"
fi
